# Generated by Django 4.2.5 on 2024-01-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robertoapp', '0001_initial'),
    ]

    operations = [
    ]
